/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import DAO.CadastrarDAO;
import DTO.CadastroAlunos;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author 3°Ano Info
 */

public class CadastrosAlunos extends javax.swing.JFrame {
     static String foto;
    /**
     * Creates new form CadastrosAlunos
     */
    public CadastrosAlunos() {
        initComponents();
        
    }
    
    JFileChooser chooser = new JFileChooser();
    File f;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnCarregarImegem = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtNomeAluno = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtMatriculaAluno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        cbTurmaAluno = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        btnCadastrarAlunos = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));
        jPanel2.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Alef", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(" Foto:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(150, 30, 70, 60);

        btnCarregarImegem.setBackground(new java.awt.Color(51, 153, 255));
        btnCarregarImegem.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnCarregarImegem.setForeground(new java.awt.Color(255, 255, 255));
        btnCarregarImegem.setText("Inserir");
        btnCarregarImegem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarImegemActionPerformed(evt);
            }
        });
        jPanel2.add(btnCarregarImegem);
        btnCarregarImegem.setBounds(130, 220, 110, 40);

        jLabel8.setFont(new java.awt.Font("Alef", 0, 25)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Pesquisar");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(30, 280, 120, 50);
        jPanel2.add(jSeparator5);
        jSeparator5.setBounds(30, 330, 270, 10);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/analysis256_24853 (2).png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel9);
        jLabel9.setBounds(110, 350, 130, 140);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Alef", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("     Voltar");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 0, 120, 40);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(40, 510, 120, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delete_102866_1.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1);
        jLabel1.setBounds(330, 10, 30, 30);

        jPanel4.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Alef", 0, 15)); // NOI18N
        jLabel10.setText("  Foto do Aluno");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(0, 0, 110, 130);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(130, 80, 110, 130);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(500, 0, 370, 570);

        jPanel3.setBackground(new java.awt.Color(16, 38, 82));
        jPanel3.setLayout(null);

        txtNomeAluno.setBackground(new java.awt.Color(16, 38, 82));
        txtNomeAluno.setFont(new java.awt.Font("Alef", 0, 15)); // NOI18N
        txtNomeAluno.setForeground(new java.awt.Color(255, 255, 255));
        txtNomeAluno.setBorder(null);
        txtNomeAluno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeAlunoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeAlunoKeyReleased(evt);
            }
        });
        jPanel3.add(txtNomeAluno);
        txtNomeAluno.setBounds(120, 160, 240, 30);
        jPanel3.add(jSeparator1);
        jSeparator1.setBounds(120, 190, 240, 10);

        jLabel2.setFont(new java.awt.Font("Alef", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome:");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(120, 130, 60, 30);

        txtMatriculaAluno.setBackground(new java.awt.Color(16, 38, 82));
        txtMatriculaAluno.setFont(new java.awt.Font("Alef", 0, 15)); // NOI18N
        txtMatriculaAluno.setForeground(new java.awt.Color(255, 255, 255));
        txtMatriculaAluno.setBorder(null);
        txtMatriculaAluno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMatriculaAlunoKeyPressed(evt);
            }
        });
        jPanel3.add(txtMatriculaAluno);
        txtMatriculaAluno.setBounds(120, 270, 240, 30);

        jLabel3.setFont(new java.awt.Font("Alef", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Matrícula:");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(120, 230, 110, 50);
        jPanel3.add(jSeparator2);
        jSeparator2.setBounds(120, 300, 240, 10);

        jLabel4.setFont(new java.awt.Font("Alef", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Turma:");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(120, 320, 130, 50);
        jPanel3.add(jSeparator3);
        jSeparator3.setBounds(120, 400, 240, 20);

        cbTurmaAluno.setFont(new java.awt.Font("Alef", 0, 13)); // NOI18N
        cbTurmaAluno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione:", "Informática", "Administração", "Enfermagem" }));
        cbTurmaAluno.setBorder(null);
        cbTurmaAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTurmaAlunoActionPerformed(evt);
            }
        });
        jPanel3.add(cbTurmaAluno);
        cbTurmaAluno.setBounds(120, 360, 240, 40);

        jLabel11.setFont(new java.awt.Font("Alef", 1, 30)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText(" Cadastro de Alunos");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(30, 30, 300, 30);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Student-id_35758.png"))); // NOI18N
        jPanel3.add(jLabel12);
        jLabel12.setBounds(350, 60, 70, 70);
        jPanel3.add(jSeparator4);
        jSeparator4.setBounds(20, 70, 470, 10);

        btnCadastrarAlunos.setBackground(new java.awt.Color(16, 38, 82));
        btnCadastrarAlunos.setFont(new java.awt.Font("Alef", 0, 15)); // NOI18N
        btnCadastrarAlunos.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrarAlunos.setText("Cadastrar");
        btnCadastrarAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarAlunosActionPerformed(evt);
            }
        });
        btnCadastrarAlunos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCadastrarAlunosKeyPressed(evt);
            }
        });
        jPanel3.add(btnCadastrarAlunos);
        btnCadastrarAlunos.setBounds(120, 450, 130, 40);
        jPanel3.add(jSeparator6);
        jSeparator6.setBounds(290, 610, 0, 2);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 500, 570);

        setSize(new java.awt.Dimension(870, 569));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 private void LimparMatricula() {
        txtNomeAluno.setText("");
        txtMatriculaAluno.setText("");
        cbTurmaAluno.setSelectedIndex(0);
        jLabel10.setIcon(null);
        jLabel10.revalidate();
        
        
    }
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void btnCadastrarAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarAlunosActionPerformed
     if(txtNomeAluno.getText().equals("")){
         JOptionPane.showMessageDialog(null, "Campo nome vazio");
     } else if(txtMatriculaAluno.getText().equals("")){
         JOptionPane.showMessageDialog(null, "Campo matricula vazio");
     } else if(cbTurmaAluno.getSelectedItem().equals("Selecione:")){
         JOptionPane.showMessageDialog(null, "Campo turma vazio");
     } else {
         CadastrarAlunos();
         LimparMatricula();
     }
     
        
    }//GEN-LAST:event_btnCadastrarAlunosActionPerformed

    private void txtNomeAlunoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeAlunoKeyReleased

    }//GEN-LAST:event_txtNomeAlunoKeyReleased

    private void cbTurmaAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTurmaAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTurmaAlunoActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
         DiracionamentoPB tela = new DiracionamentoPB();
         tela.setVisible(true);
         dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
         Pesquisar tela = new Pesquisar();
         tela.setVisible(true);
         dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void txtNomeAlunoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeAlunoKeyPressed

    }//GEN-LAST:event_txtNomeAlunoKeyPressed

    private void txtMatriculaAlunoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMatriculaAlunoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatriculaAlunoKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
    
    }//GEN-LAST:event_formKeyPressed

    private void btnCarregarImegemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarImegemActionPerformed
       chooser.showOpenDialog(null);
        f = chooser.getSelectedFile();
         foto = f.getAbsolutePath();
        jLabel10.setText(foto);
        
        /* OPCIONAL - Código para definir o tamanho da imagem na tela */
        ImageIcon imageIcon = new ImageIcon(f.getPath()); // load the image to a imageIcon
        Image image = imageIcon.getImage(); // transform it 
        Image newimg = image.getScaledInstance(110,130,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way 
        /* Fim do código do redimensionamento */
        
        ImageIcon icon = new ImageIcon(newimg);
        jLabel10.setIcon(icon);  
    }//GEN-LAST:event_btnCarregarImegemActionPerformed

    private void btnCadastrarAlunosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCadastrarAlunosKeyPressed
       
    }//GEN-LAST:event_btnCadastrarAlunosKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrosAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrosAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrosAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrosAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrosAlunos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarAlunos;
    private javax.swing.JButton btnCarregarImegem;
    private javax.swing.JComboBox<String> cbTurmaAluno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField txtMatriculaAluno;
    private javax.swing.JTextField txtNomeAluno;
    // End of variables declaration//GEN-END:variables

private void CadastrarAlunos(){
     try{
         
        String nome, turma, matricula;
        
        nome = txtNomeAluno.getText();
        matricula = txtMatriculaAluno.getText();
        turma = cbTurmaAluno.getSelectedItem()+"";
        
         CadastroAlunos objcadastroalunos = new CadastroAlunos();
         objcadastroalunos.setAluno(nome);
         objcadastroalunos.setTurma(turma);
         objcadastroalunos.setMatricula(matricula);
         objcadastroalunos.setFoto(foto);
         
         CadastrarDAO objcadastrardao = new CadastrarDAO();
         objcadastrardao.cadastrarAluno(objcadastroalunos);
         
         JOptionPane.showMessageDialog(null,"Aluno Cadastrado");
       }catch(Exception e){
           JOptionPane.showMessageDialog(null,"Aluno não Cadastrado: "+e);
       }
}



}
