/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import static visao.Pesquisar.idaluno;
import static visao.Pesquisar.matriculaaluno;
import static visao.Pesquisar.nomealuno;
import static visao.Pesquisar.turmaaluno;
import DTO.CadastroAlunos;
import DAO.CadastrarDAO;
import DAO.FrequenciaAlunos;
import java.awt.Image;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static visao.Pesquisar.foto;
import DTO.FrequenciaDTO;
        

/**
 *
 * @author 3°Ano Info
 */
public class EditarUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form EditarUsuarios
     */
    public EditarUsuarios() {
        initComponents();
        txtIdAlunoEdit.setText(idaluno);
        txtNomeAlunoEdit.setText(nomealuno);
        txtMatriculaAlunoEdit.setText(matriculaaluno);
        txtTurmaAlunoEdit.setText(turmaaluno);
        carregarFoto();
    }
    private void carregarFoto(){
      CadastrarDAO objcadastrardao = new CadastrarDAO();
        ResultSet rs = objcadastrardao.carrCampos(matriculaaluno);

        try {
            while (rs.next()) {
                ImageIcon imageIcon = new ImageIcon(rs.getString("foto_aluno"));

                Image image = imageIcon.getImage(); // transform it 
                Image newimg = image.getScaledInstance(120, 140, java.awt.Image.SCALE_SMOOTH); // scale it the smooth way 
                /* Fim do código do redimensionamento */

                ImageIcon icon = new ImageIcon(newimg);
          
                moldura.setIcon(icon);
            }
        } catch (SQLException ex) {
            Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbprocurar = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtTurmaAlunoEdit = new javax.swing.JTextField();
        txtIdAlunoEdit = new javax.swing.JTextField();
        txtNomeAlunoEdit = new javax.swing.JTextField();
        txtMatriculaAlunoEdit = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        moldura = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 0, 0);

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6);
        jPanel6.setBounds(0, 0, 10, 580);

        jLabel3.setFont(new java.awt.Font("Alef", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Id_Aluno");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 90, 90, 30);

        jLabel6.setFont(new java.awt.Font("Alef", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nome:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 160, 70, 30);

        jLabel7.setFont(new java.awt.Font("Alef", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Matricula:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(310, 90, 110, 30);

        jLabel8.setFont(new java.awt.Font("Alef", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Faltas:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(160, 320, 80, 50);

        tbprocurar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Presença:", "Data:"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbprocurar);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(40, 370, 450, 180);

        jLabel12.setFont(new java.awt.Font("Alef", 1, 25)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Procurar");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(90, 10, 120, 40);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delete_102866_1.png"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel14);
        jLabel14.setBounds(600, 0, 50, 50);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar03.png"))); // NOI18N
        jPanel1.add(jLabel16);
        jLabel16.setBounds(40, 0, 50, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/useredicao.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(500, 360, 130, 210);

        btnAlterar.setBackground(new java.awt.Color(51, 153, 255));
        btnAlterar.setFont(new java.awt.Font("Alef", 1, 15)); // NOI18N
        btnAlterar.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAlterar);
        btnAlterar.setBounds(40, 240, 110, 40);

        btnExcluir.setBackground(new java.awt.Color(51, 153, 255));
        btnExcluir.setFont(new java.awt.Font("Alef", 1, 15)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(btnExcluir);
        btnExcluir.setBounds(170, 240, 110, 40);

        jLabel15.setFont(new java.awt.Font("Alef", 0, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Turma:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(310, 150, 100, 50);

        txtTurmaAlunoEdit.setBackground(new java.awt.Color(51, 153, 255));
        txtTurmaAlunoEdit.setFont(new java.awt.Font("Alef", 0, 15)); // NOI18N
        txtTurmaAlunoEdit.setForeground(new java.awt.Color(255, 255, 255));
        txtTurmaAlunoEdit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(txtTurmaAlunoEdit);
        txtTurmaAlunoEdit.setBounds(310, 190, 240, 30);

        txtIdAlunoEdit.setEditable(false);
        txtIdAlunoEdit.setBackground(new java.awt.Color(51, 153, 255));
        txtIdAlunoEdit.setFont(new java.awt.Font("Alef", 0, 15)); // NOI18N
        txtIdAlunoEdit.setForeground(new java.awt.Color(255, 255, 255));
        txtIdAlunoEdit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(txtIdAlunoEdit);
        txtIdAlunoEdit.setBounds(40, 120, 240, 30);

        txtNomeAlunoEdit.setBackground(new java.awt.Color(51, 153, 255));
        txtNomeAlunoEdit.setFont(new java.awt.Font("Alef", 0, 15)); // NOI18N
        txtNomeAlunoEdit.setForeground(new java.awt.Color(255, 255, 255));
        txtNomeAlunoEdit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(txtNomeAlunoEdit);
        txtNomeAlunoEdit.setBounds(40, 190, 240, 30);

        txtMatriculaAlunoEdit.setBackground(new java.awt.Color(51, 153, 255));
        txtMatriculaAlunoEdit.setFont(new java.awt.Font("Alef", 0, 15)); // NOI18N
        txtMatriculaAlunoEdit.setForeground(new java.awt.Color(255, 255, 255));
        txtMatriculaAlunoEdit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(txtMatriculaAlunoEdit);
        txtMatriculaAlunoEdit.setBounds(310, 120, 240, 30);

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setFont(new java.awt.Font("Alef", 0, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(40, 320, 110, 40);

        jButton3.setBackground(new java.awt.Color(51, 153, 255));
        jButton3.setFont(new java.awt.Font("Alef", 0, 15)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Baixar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(390, 320, 100, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(230, 0, 650, 580);

        jPanel4.setBackground(new java.awt.Color(16, 38, 82));
        jPanel4.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel3);
        jPanel3.setBounds(0, 0, 230, 10);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Alef", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" Alunos");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(60, 30, 110, 40);
        jPanel4.add(jSeparator1);
        jSeparator1.setBounds(30, 70, 150, 10);

        jPanel5.setBackground(new java.awt.Color(16, 38, 82));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel5.setLayout(null);

        moldura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fotoaluno02.png"))); // NOI18N
        jPanel5.add(moldura);
        moldura.setBounds(0, 0, 120, 140);

        jPanel4.add(jPanel5);
        jPanel5.setBounds(60, 110, 120, 140);

        jPanel7.setBackground(new java.awt.Color(16, 38, 82));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel7.setLayout(null);

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/digitalaluno02.png"))); // NOI18N
        jPanel7.add(jLabel5);
        jLabel5.setBounds(10, 10, 90, 120);

        jPanel4.add(jPanel7);
        jPanel7.setBounds(30, 280, 0, 0);

        jPanel8.setBackground(new java.awt.Color(16, 38, 82));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel8.setLayout(null);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/digitalaluno02.png"))); // NOI18N
        jPanel8.add(jLabel11);
        jLabel11.setBounds(20, 0, 100, 140);

        jPanel4.add(jPanel8);
        jPanel8.setBounds(60, 300, 120, 140);

        jButton2.setBackground(new java.awt.Color(16, 38, 82));
        jButton2.setFont(new java.awt.Font("Alef", 1, 15)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Voltar");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(16, 38, 82)));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel4.add(jButton2);
        jButton2.setBounds(20, 510, 100, 40);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 230, 580);

        setSize(new java.awt.Dimension(872, 573));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        Pesquisar tela = new Pesquisar();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        
        int confirm = JOptionPane.showConfirmDialog(this, "Deseja editar esses dados?", "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(confirm==JOptionPane.YES_OPTION){
        AlterarAlunos();
        listarValoresAlunos();
        txtIdAlunoEdit.setText("");
        txtNomeAlunoEdit.setText("");
        txtMatriculaAlunoEdit.setText("");
        txtTurmaAlunoEdit.setText("");
        txtNomeAlunoEdit.requestFocus();
        
        } else if(confirm==JOptionPane.NO_OPTION){
            
        }
        
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int confirmar = JOptionPane.showConfirmDialog(this,"Deseja excluir esses dados?", "Confirmar", JOptionPane.YES_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(confirmar==JOptionPane.YES_OPTION){
        ExcluirAlunos();
        Pesquisar tela = new Pesquisar();
        tela.setVisible(true);
        dispose();
        listarValoresAlunos();
        txtIdAlunoEdit.setText("");
        txtNomeAlunoEdit.setText("");
        txtMatriculaAlunoEdit.setText("");
        txtTurmaAlunoEdit.setText("");
        txtNomeAlunoEdit.requestFocus();
        }else if(confirmar==JOptionPane.NO_OPTION){
            
        }
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        listarValoresAlunos02();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            tbprocurar.print(javax.swing.JTable.PrintMode.FIT_WIDTH,
                    new java.text.MessageFormat("Frequência do Aluno"), // titulo da pagina
                    new java.text.MessageFormat("Page {0}"));
        } catch (java.awt.print.PrinterException e) {
            JOptionPane.showMessageDialog(this, "Erro ao tentar imprimir!\n"
                    + e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel moldura;
    private javax.swing.JTable tbprocurar;
    private javax.swing.JTextField txtIdAlunoEdit;
    private javax.swing.JTextField txtMatriculaAlunoEdit;
    private javax.swing.JTextField txtNomeAlunoEdit;
    private javax.swing.JTextField txtTurmaAlunoEdit;
    // End of variables declaration//GEN-END:variables

    private void AlterarAlunos() {
        int id_Aluno;
        String aluno, matricula, turma;

        id_Aluno = Integer.parseInt(txtIdAlunoEdit.getText());
        aluno = txtNomeAlunoEdit.getText();
        matricula = txtMatriculaAlunoEdit.getText();
        turma = txtTurmaAlunoEdit.getText();

        CadastroAlunos objcadastroalunos = new CadastroAlunos();
        objcadastroalunos.setId_aluno(id_Aluno);
        objcadastroalunos.setAluno(aluno);
        objcadastroalunos.setMatricula(matricula);
        objcadastroalunos.setTurma(turma);

        CadastrarDAO objcacadastrardao = new CadastrarDAO();
        objcacadastrardao.alterarAlunos(objcadastroalunos);

        JOptionPane.showMessageDialog(null, "Cadastro editado com sucesso");
    }

    
    private void ExcluirAlunos(){
        int id_Aluno;
        
        id_Aluno = Integer.parseInt(txtIdAlunoEdit.getText());
        
        CadastroAlunos objcadastroalunos = new CadastroAlunos();
        objcadastroalunos.setId_aluno(id_Aluno);
        
        CadastrarDAO objcadastrardao = new CadastrarDAO();
        objcadastrardao.excluirAlunos(objcadastroalunos);
        
         JOptionPane.showMessageDialog(null, "Cadastro Excluido com sucesso");
    }

    private void listarValoresAlunos() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    public void listarValoresAlunos02() {
        try {

            FrequenciaAlunos objfrequenciaalunos = new FrequenciaAlunos();

            DefaultTableModel model = (DefaultTableModel) tbprocurar.getModel();
            model.setNumRows(0);

            ArrayList<FrequenciaDTO> lista = objfrequenciaalunos.PesquisarFrequencia02(nomealuno);

            for (int num = 0; num < lista.size(); num++) {
                model.addRow(new Object[]{ 
                  
                    lista.get(num).getFrequencia(),
                    lista.get(num).getData()

                });
            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Listar Valores: " + erro);
        }
    }
    

}
