/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import DAO.CadastrarDAO;
import DAO.FrequenciaAlunos;
import DTO.CadastroAlunos;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import DTO.FrequenciaDTO;

/**
 *
 * @author 3°Ano Info
 */
public class Frequencia extends javax.swing.JFrame {

    /**
     * Creates new form Frequencia
     */
    public Frequencia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbFrequencia = new javax.swing.JTable();
        btnPesquisarFrequencia = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtPesquisarFrequenciaAlunos = new javax.swing.JTextField();
        comFrequencia = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 153, 255));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setFont(new java.awt.Font("Alef", 0, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Voltar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 500, 110, 40);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(null);

        tbFrequencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome:", "Turma:", "Frequência:", "Data:"
            }
        ));
        jScrollPane1.setViewportView(tbFrequencia);
        if (tbFrequencia.getColumnModel().getColumnCount() > 0) {
            tbFrequencia.getColumnModel().getColumn(2).setHeaderValue("Frequência:");
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 140, 670, 340);

        btnPesquisarFrequencia.setBackground(new java.awt.Color(51, 153, 255));
        btnPesquisarFrequencia.setFont(new java.awt.Font("Alef", 0, 15)); // NOI18N
        btnPesquisarFrequencia.setForeground(new java.awt.Color(255, 255, 255));
        btnPesquisarFrequencia.setText("Pesquisar");
        btnPesquisarFrequencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarFrequenciaActionPerformed(evt);
            }
        });
        jPanel1.add(btnPesquisarFrequencia);
        btnPesquisarFrequencia.setBounds(570, 90, 120, 40);

        jButton2.setBackground(new java.awt.Color(51, 153, 255));
        jButton2.setFont(new java.awt.Font("Alef", 0, 20)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Baixar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(150, 500, 110, 40);

        txtPesquisarFrequenciaAlunos.setBackground(new java.awt.Color(51, 153, 255));
        txtPesquisarFrequenciaAlunos.setFont(new java.awt.Font("Alef", 0, 15)); // NOI18N
        txtPesquisarFrequenciaAlunos.setForeground(new java.awt.Color(255, 255, 255));
        txtPesquisarFrequenciaAlunos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(txtPesquisarFrequenciaAlunos);
        txtPesquisarFrequenciaAlunos.setBounds(200, 90, 350, 40);

        comFrequencia.setFont(new java.awt.Font("Alef", 0, 15)); // NOI18N
        comFrequencia.setForeground(new java.awt.Color(255, 255, 255));
        comFrequencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "Turma", "Data" }));
        jPanel1.add(comFrequencia);
        comFrequencia.setBounds(20, 90, 160, 40);

        jLabel2.setFont(new java.awt.Font("Alef", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pesquisar por:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 40, 140, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delete_102866_1.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1);
        jLabel1.setBounds(830, 0, 50, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/impressao-digital (1).png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(720, 170, 140, 220);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);
        jPanel1.add(jPanel2);
        jPanel2.setBounds(770, 0, 0, 560);

        jPanel3.setLayout(null);
        jPanel1.add(jPanel3);
        jPanel3.setBounds(380, 50, 390, 0);

        jLabel4.setFont(new java.awt.Font("Alef", 0, 25)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Lista de Frequência");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 0, 230, 60);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(20, 50, 610, 10);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 870, 560);

        setSize(new java.awt.Dimension(869, 560));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        Pesquisar tela = new Pesquisar();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void btnPesquisarFrequenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarFrequenciaActionPerformed

        pesquisarValoresAlunos(txtPesquisarFrequenciaAlunos.getText());
    }//GEN-LAST:event_btnPesquisarFrequenciaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            tbFrequencia.print(javax.swing.JTable.PrintMode.FIT_WIDTH,
                    new java.text.MessageFormat("Frequência dos Alunos"), // titulo da pagina
                    new java.text.MessageFormat("Page {0}"));
        } catch (java.awt.print.PrinterException e) {
            JOptionPane.showMessageDialog(this, "Erro ao tentar imprimir!\n"
                    + e.getMessage());
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frequencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frequencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frequencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frequencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frequencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisarFrequencia;
    private javax.swing.JComboBox<String> comFrequencia;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tbFrequencia;
    private javax.swing.JTextField txtPesquisarFrequenciaAlunos;
    // End of variables declaration//GEN-END:variables
public void listarValoresFrequencia() {
        try {

            FrequenciaAlunos objfrequenciaalunos = new FrequenciaAlunos();

            DefaultTableModel model = (DefaultTableModel) tbFrequencia.getModel();
            model.setNumRows(0);

            ArrayList<FrequenciaDTO> lista = objfrequenciaalunos.PesquisarFrequencia();

            for (int num = 0; num < lista.size(); num++) {
                model.addRow(new Object[]{
                    lista.get(num).getNome(),
                    lista.get(num).getTurma(),
                    lista.get(num).getFrequencia(),
                    lista.get(num).getData()

                });
            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Listar Valores: " + erro);
        }
    }

    public void pesquisarValoresAlunos(String frequencia) {

        final String NOME = "nome";
        final String TURMA = "turma";
        final String DATA = "data";
        final String FREQUENCIA = "frequencia";
        FrequenciaAlunos objfrequenciaalunos = new FrequenciaAlunos();
        if (comFrequencia.getSelectedItem().equals("Nome")) {
            try {
                DefaultTableModel model = (DefaultTableModel) tbFrequencia.getModel();
                model.setNumRows(0);

                ArrayList<FrequenciaDTO> lista = objfrequenciaalunos.readForFrequencia(frequencia, NOME);

                for (int num = 0; num < lista.size(); num++) {
                    model.addRow(new Object[]{
                        lista.get(num).getNome(),
                        lista.get(num).getTurma(),
                        lista.get(num).getFrequencia(),
                        lista.get(num).getData()

                    });
                }

            } catch (Exception erro) {
                JOptionPane.showMessageDialog(null, "Listar Valores: " + erro);
            }

        } else if (comFrequencia.getSelectedItem().equals("Turma")) {
            try {
                DefaultTableModel model = (DefaultTableModel) tbFrequencia.getModel();
                model.setNumRows(0);

                ArrayList<FrequenciaDTO> lista = objfrequenciaalunos.readForFrequencia(frequencia, TURMA);

                for (int num = 0; num < lista.size(); num++) {
                    model.addRow(new Object[]{
                        lista.get(num).getNome(),
                        lista.get(num).getTurma(),
                        lista.get(num).getFrequencia(),
                        lista.get(num).getData()

                    });
                }

            } catch (Exception erro) {
                JOptionPane.showMessageDialog(null, "Listar Valores: " + erro);
            }
        } else if (comFrequencia.getSelectedItem().equals("Data")) {
            try {
                DefaultTableModel model = (DefaultTableModel) tbFrequencia.getModel();
                model.setNumRows(0);

                ArrayList<FrequenciaDTO> lista = objfrequenciaalunos.readForFrequencia(frequencia, TURMA);

                for (int num = 0; num < lista.size(); num++) {
                    model.addRow(new Object[]{
                        lista.get(num).getNome(),
                        lista.get(num).getTurma(),
                        lista.get(num).getFrequencia(),
                        lista.get(num).getData()

                    });
                }

            } catch (Exception erro) {
                JOptionPane.showMessageDialog(null, "Listar Valores: " + erro);
            }
        }
    }

}
